// Auto-generated by Clasptek Vercel Build Script — DO NOT COMMIT REAL SECRETS
window.__CLASPTEK_ENV__ = {
  SUPABASE_URL: "https://logaawoigfxnisimfatf.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_VbAnvwhA28SV_PmLcEiTdg_12cc7Or9"
};
